// -----------------------------------------------------------------------------
// ssv_audio_debug_overlay.sv -- GENERATED by scratchpad gen_overlay.py.
//
// Fullscreen ES5506 audio-debug text screen. Replaces the game picture (the
// core keeps running underneath, video pipeline untouched) with a black
// screen carrying every audio-path observable needed to root-cause warped
// music/SFX: per-voice register shadows (CR/FC/ACCUM/START/END/VOL/ECOUNT/
// K1/K2) captured at the engine's own eng_snap, per-frame event counters
// (sample ticks, underruns, host writes/reads, register commits, IRQ sets),
// SDRAM p4 fetch latency stats (last/max/frame-max plus >64/>128/>256-cycle
// bucket counts), output L/R levels with per-frame min/max (clipping check),
// a 32-bit running-voice mask, and a 12-entry newest-first host commit log.
//
// Grid: 84x40 cells of 4x6 px (3x5 glyph) over the 336x240 active raster.
// All display values are latched at frame start so a screenshot is coherent.
// -----------------------------------------------------------------------------

module ssv_audio_debug_overlay (
    input  logic        clk,
    input  logic        rst,
    input  logic        en,

    // raster position from ssv_video_timing (active region starts at 0,0)
    input  logic        ce_pixel,
    input  logic [8:0]  hcnt,
    input  logic [8:0]  vcnt,
    input  logic [8:0]  active_width,
    input  logic [8:0]  active_height,
    input  logic [23:0] rgb_in,
    output logic [23:0] rgb_out,

    // engine snapshot bus (regs -> voice engine, valid on eng_snap)
    input  logic        eng_snap,
    input  logic [4:0]  eng_voice,
    input  logic [15:0] eng_cr,
    input  logic [16:0] eng_fc,
    input  logic [31:0] eng_accum,
    input  logic [31:0] eng_start,
    input  logic [31:0] eng_end,
    input  logic [15:0] eng_lvol,
    input  logic [15:0] eng_rvol,
    input  logic [8:0]  eng_ecount,
    input  logic [15:0] eng_k1,
    input  logic [15:0] eng_k2,

    // engine writeback pulses (voice -> regs), for the race detectors
    input  logic        eng_wr_accum,
    input  logic [31:0] eng_accum_w,
    input  logic        eng_wr_cr,
    input  logic        eng_wr_filt,
    input  logic        eng_wr_env,
    // which ES5506 CR banks this cartridge populates (cfg.bank_valid)
    input  logic [3:0]  bank_valid,

    // engine / IRQ events
    input  logic        sample_tick,
    input  logic        underrun,
    input  logic        irq_n,
    input  logic        irq_set,
    input  logic [4:0]  irq_voice,
    input  logic [4:0]  active_voices,
    input  logic [6:0]  current_page,

    // host interface activity
    input  logic        commit,
    input  logic [6:0]  commit_page,
    input  logic [3:0]  commit_reg,
    input  logic [31:0] commit_data,
    input  logic        host_we,
    input  logic        host_re,
    input  logic        ce_snd,

    // sample-fetch SDRAM port (p4)
    input  logic        p4_req,
    input  logic        p4_ack,

    // final mix
    input  logic signed [15:0] audio_l,
    input  logic signed [15:0] audio_r
);

// ---------------------------------------------------------------------------
// Per-voice register shadow, written on the engine's own snapshot pulse so it
// always reflects exactly what the voice engine consumed (accum is written
// back by the engine every sample, so this shows the live phase accumulator).
// ---------------------------------------------------------------------------
localparam int REC_W = 202;
logic [REC_W-1:0] shadow [0:31];
always_ff @(posedge clk) begin
    if (eng_snap)
        shadow[eng_voice] <= {eng_cr, eng_fc, eng_accum, eng_start, eng_end,
                              eng_lvol, eng_rvol, eng_ecount, eng_k1, eng_k2};
end

logic [4:0]       shadow_rd_addr;
logic [REC_W-1:0] shadow_q;
always_ff @(posedge clk) shadow_q <= shadow[shadow_rd_addr];

// ---------------------------------------------------------------------------
// Running-voice mask (CR STOP0|STOP1 both clear) captured per snapshot.
// ---------------------------------------------------------------------------
logic [31:0] run_mask;
always_ff @(posedge clk) begin
    if (rst) run_mask <= 32'd0;
    else if (eng_snap) run_mask[eng_voice] <= ~(eng_cr[0] | eng_cr[1]);
end

// ---------------------------------------------------------------------------
// Audio-race detectors. One counter/latch per corruption scenario from the
// 2026-08-26 audio-path audit, so a single gameplay video attributes the
// warped-sound events to a mechanism:
//
//  TP  teleport: at eng_snap the voice's ACCUM differs from the engine's own
//      last writeback with no intervening host ACCUM commit -- a lost or
//      corrupted register-file write (MLAB RDW garbage, dropped deferral).
//      Latches voice, expected, seen, frame.
//  RA  runaway: running voice snapshotted with ACCUM outside [START,END] --
//      the audible warped-fragment state itself (stuck LEI, teleport
//      aftermath). Latches voice, CR, ACCUM, frame.
//  F1  host commit to an UNPROTECTED field (FC/LVRAMP/RVRAMP/K2RAMP/K1RAMP
//      of bank0, START/END/ACCUM of bank1) of the voice being snapshotted,
//      landing exactly in the MLAB read-during-write window (commit pulse
//      coincides with eng_snap). Cause condition for TP. Latches
//      voice/reg/bank/frame.
//  F2  host CR commit to the in-flight voice between its snapshot and the
//      engine's CR writeback that same scan -- stale loop-transition masks
//      merge over the fresh CR. Latches frame.
//  CS  CR commit adjacent to the voice's own snapshot (the cr_snap_missed /
//      voided-scan engagement rate -- benign by design, baseline for F2).
//  F3  eng_snap inside a host read-steal window (flush/hold hazards).
//  F4  as F3 but with a same-voice commit 1-3 cycles earlier (stale-_h
//      fresh-bit hole).
//  DF  host commit coinciding with an engine writeback pulse (deferral
//      machinery engagement; a skid overflow would silently drop here).
//  CX  snapshot CR with LEI set while LPE/BLE still set -- illegal merge
//      signature of the stale-mask class.
//  BK  running voice whose CR selects an unpopulated sample bank -- CR
//      corruption signature (silent/wrong voice).
//  SE  running forward voice with START > END -- register-pair corruption.
//  PQ  snapshots with CR.IRQ pending (promotion backlog indicator).
// ---------------------------------------------------------------------------
logic [31:0] exp_accum [0:31];
logic [31:0] exp_valid;
logic [31:0] acc_dirty;

logic [15:0] det_tp_cnt,  det_ra_cnt,  det_f1_cnt, det_f2_cnt;
logic [15:0] det_cs_cnt,  det_f3_cnt,  det_f4_cnt, det_df_cnt;
logic [15:0] det_cx_cnt,  det_bk_cnt,  det_se_cnt, det_pq_cnt;
logic [4:0]  det_tp_voice, det_ra_voice, det_f1_voice;
logic [31:0] det_tp_exp, det_tp_seen, det_ra_accum;
logic [15:0] det_ra_cr;
logic [3:0]  det_f1_reg;
logic        det_f1_bank;
logic [15:0] det_tp_frame, det_ra_frame, det_f1_frame, det_f2_frame;

logic        f2_arm;
logic [4:0]  f2_voice;
logic        re_d1, re_d2, re_d3;
logic        cvm_d1, cvm_d2, cvm_d3;

wire commit_vmatch = commit && (commit_page < 7'h40);
wire [4:0] commit_voice = commit_page[4:0];
wire commit_accum   = commit_vmatch &&  commit_page[5] && (commit_reg == 4'h3);
wire commit_cr      = commit_vmatch && (commit_reg == 4'h0);
// Fields with neither host_fresh protection nor engine ownership: FC(1),
// LVRAMP(3), RVRAMP(5), K2RAMP(8), K1RAMP(A) on bank0; START(1), END(2),
// ACCUM(3) on bank1. A garbage snapshot of any of these can propagate into a
// persistent engine writeback of another field.
wire commit_f1reg = commit_vmatch &&
    (commit_page[5]
        ? (commit_reg == 4'h1 || commit_reg == 4'h2 || commit_reg == 4'h3)
        : (commit_reg == 4'h1 || commit_reg == 4'h3 || commit_reg == 4'h5 ||
           commit_reg == 4'h8 || commit_reg == 4'ha));
wire commit_this_voice = commit_vmatch && (commit_voice == eng_voice);

wire snap_running  = ~(eng_cr[0] | eng_cr[1]);
wire snap_outrange = snap_running &&
                     ((eng_accum > eng_end) || (eng_accum < eng_start));
wire eng_write_any = eng_wr_accum | eng_wr_cr | eng_wr_filt | eng_wr_env;
wire read_window   = host_re || re_d1 || re_d2 || re_d3;
// live frame number (disp_frame increments once per frame below)
wire [15:0] frame_lo = disp_frame[15:0];

always_ff @(posedge clk) begin
    re_d1 <= host_re; re_d2 <= re_d1; re_d3 <= re_d2;
    cvm_d1 <= commit_this_voice; cvm_d2 <= cvm_d1; cvm_d3 <= cvm_d2;
    if (rst) begin
        exp_valid <= '0; acc_dirty <= '0;
        det_tp_cnt <= '0; det_ra_cnt <= '0; det_f1_cnt <= '0; det_f2_cnt <= '0;
        det_cs_cnt <= '0; det_f3_cnt <= '0; det_f4_cnt <= '0; det_df_cnt <= '0;
        det_cx_cnt <= '0; det_bk_cnt <= '0; det_se_cnt <= '0; det_pq_cnt <= '0;
        det_tp_voice <= '0; det_ra_voice <= '0; det_f1_voice <= '0;
        det_tp_exp <= '0; det_tp_seen <= '0; det_ra_accum <= '0;
        det_ra_cr <= '0; det_f1_reg <= '0; det_f1_bank <= 1'b0;
        det_tp_frame <= '0; det_ra_frame <= '0;
        det_f1_frame <= '0; det_f2_frame <= '0;
        f2_arm <= 1'b0; f2_voice <= '0;
    end else begin
        // --- TP arm: remember the engine's own last ACCUM writeback. The
        // regs file drops that writeback when the host refreshed ACCUM since
        // the snapshot (host_fresh), so mirror that window with acc_dirty and
        // do not arm from a writeback the regs file will discard.
        if (eng_wr_accum && !acc_dirty[eng_voice]) begin
            exp_accum[eng_voice] <= eng_accum_w;
            exp_valid[eng_voice] <= 1'b1;
        end

        if (eng_snap) begin
            acc_dirty[eng_voice] <= 1'b0;

            // --- TP check ---
            if (exp_valid[eng_voice] &&
                (eng_accum != exp_accum[eng_voice])) begin
                det_tp_cnt   <= det_tp_cnt + 1'd1;
                det_tp_voice <= eng_voice;
                det_tp_exp   <= exp_accum[eng_voice];
                det_tp_seen  <= eng_accum;
                det_tp_frame <= frame_lo;
                exp_valid[eng_voice] <= 1'b0; // one event per divergence
            end

            // --- RA / CX / BK / SE / PQ state checks ---
            if (snap_outrange) begin
                det_ra_cnt   <= det_ra_cnt + 1'd1;
                det_ra_voice <= eng_voice;
                det_ra_cr    <= eng_cr;
                det_ra_accum <= eng_accum;
                det_ra_frame <= frame_lo;
            end
            if (eng_cr[2] && (eng_cr[3] || eng_cr[4]))
                det_cx_cnt <= det_cx_cnt + 1'd1;
            if (snap_running && !bank_valid[eng_cr[15:14]])
                det_bk_cnt <= det_bk_cnt + 1'd1;
            if (snap_running && !eng_cr[6] && (eng_start > eng_end))
                det_se_cnt <= det_se_cnt + 1'd1;
            if (eng_cr[7])
                det_pq_cnt <= det_pq_cnt + 1'd1;

            // --- F1: unprotected-field commit in the RDW window ---
            if (commit_f1reg && (commit_voice == eng_voice)) begin
                det_f1_cnt   <= det_f1_cnt + 1'd1;
                det_f1_voice <= commit_voice;
                det_f1_reg   <= commit_reg;
                det_f1_bank  <= commit_page[5];
                det_f1_frame <= frame_lo;
            end

            // --- CS: snap-adjacent CR commit (voided-scan engagement) ---
            if (commit_cr && (commit_voice == eng_voice))
                det_cs_cnt <= det_cs_cnt + 1'd1;

            // --- F3/F4: snapshot inside a read-steal window ---
            if (read_window) begin
                det_f3_cnt <= det_f3_cnt + 1'd1;
                if (commit_this_voice || cvm_d1 || cvm_d2 || cvm_d3)
                    det_f4_cnt <= det_f4_cnt + 1'd1;
            end

            // new scan: disarm the F2 tracker for the previous voice
            f2_arm <= 1'b0;
        end

        // --- F2: CR commit to the in-flight voice, then an engine CR
        //     writeback in the same scan (stale transition over fresh CR).
        if (commit_cr && (commit_voice == eng_voice) && !eng_snap) begin
            f2_arm   <= 1'b1;
            f2_voice <= commit_voice;
        end
        if (eng_wr_cr && f2_arm && (f2_voice == eng_voice)) begin
            det_f2_cnt   <= det_f2_cnt + 1'd1;
            det_f2_frame <= frame_lo;
            f2_arm       <= 1'b0;
        end

        // --- DF: commit racing an engine writeback (deferral engagement) ---
        if (commit && eng_write_any)
            det_df_cnt <= det_df_cnt + 1'd1;

        // host ACCUM commit supersedes the engine's remembered writeback
        if (commit_accum) begin
            exp_valid[commit_voice] <= 1'b0;
            acc_dirty[commit_voice] <= 1'b1;
        end
    end
end

// ---------------------------------------------------------------------------
// Event edge detects (some taps are level-held).
// ---------------------------------------------------------------------------
logic under_q, hostwe_q, hostre_q;
always_ff @(posedge clk) begin
    under_q  <= underrun;
    hostwe_q <= host_we;
    hostre_q <= host_re;
end
wire under_edge  = underrun && !under_q;
wire hostwe_edge = host_we  && !hostwe_q;
wire hostre_edge = host_re  && !hostre_q;

// ---------------------------------------------------------------------------
// p4 fetch latency: count clk cycles a request waits for its ack.
// ---------------------------------------------------------------------------
logic [15:0] lat_cnt;
wire p4_done = p4_req && p4_ack;
always_ff @(posedge clk) begin
    if (rst)          lat_cnt <= 16'd0;
    else if (p4_done) lat_cnt <= 16'd0;
    else if (p4_req && !(&lat_cnt)) lat_cnt <= lat_cnt + 1'd1;
end
wire [15:0] lat_now = (&lat_cnt) ? lat_cnt : lat_cnt + 1'd1;

// ---------------------------------------------------------------------------
// Frame-accumulated counters, latched into disp_* at frame start.
// ---------------------------------------------------------------------------
wire frame_pulse = ce_pixel && (hcnt == 9'd0) && (vcnt == 9'd0);

logic [15:0] c_ticks, c_under, c_commit, c_hostwr, c_hostrd, c_iset;
logic [23:0] c_cesnd, c_p4req;
logic [15:0] c_g64, c_g128, c_g256, c_latmaxf;
logic [31:0] t_under, t_p4, t_tick;
logic [15:0] latmax_sticky, lat_last;
logic signed [15:0] c_lmin, c_lmax, c_rmin, c_rmax;
logic [4:0]  last_irq_voice;

logic [31:0] disp_frame;
logic [15:0] disp_ticks, disp_under, disp_commit, disp_hostwr, disp_hostrd,
             disp_iset, disp_g64, disp_g128, disp_g256, disp_latmaxf;
logic [23:0] disp_cesnd, disp_p4req;
logic [31:0] disp_undert, disp_p4tot, disp_ticktot, disp_run;
logic [15:0] disp_al, disp_ar, disp_lmin, disp_lmax, disp_rmin, disp_rmax;
logic [4:0]  disp_av, disp_irqv;
logic [6:0]  disp_pg;
logic        disp_irqn;

// Detector panel display copies (latched per frame so video frames are
// tear-free; the underlying counters are cumulative and monotonic).
logic [15:0] dd_tp_cnt, dd_ra_cnt, dd_f1_cnt, dd_f2_cnt;
logic [15:0] dd_cs_cnt, dd_f3_cnt, dd_f4_cnt, dd_df_cnt;
logic [15:0] dd_cx_cnt, dd_bk_cnt, dd_se_cnt, dd_pq_cnt;
logic [4:0]  dd_tp_voice, dd_ra_voice, dd_f1_voice;
logic [31:0] dd_tp_exp, dd_tp_seen, dd_ra_accum;
logic [15:0] dd_ra_cr;
logic [3:0]  dd_f1_reg;
logic        dd_f1_bank;
logic [15:0] dd_tp_frame, dd_ra_frame, dd_f1_frame, dd_f2_frame;

always_ff @(posedge clk) begin
    if (rst) begin
        dd_tp_cnt <= '0; dd_ra_cnt <= '0; dd_f1_cnt <= '0; dd_f2_cnt <= '0;
        dd_cs_cnt <= '0; dd_f3_cnt <= '0; dd_f4_cnt <= '0; dd_df_cnt <= '0;
        dd_cx_cnt <= '0; dd_bk_cnt <= '0; dd_se_cnt <= '0; dd_pq_cnt <= '0;
        dd_tp_voice <= '0; dd_ra_voice <= '0; dd_f1_voice <= '0;
        dd_tp_exp <= '0; dd_tp_seen <= '0; dd_ra_accum <= '0;
        dd_ra_cr <= '0; dd_f1_reg <= '0; dd_f1_bank <= 1'b0;
        dd_tp_frame <= '0; dd_ra_frame <= '0;
        dd_f1_frame <= '0; dd_f2_frame <= '0;
    end else if (frame_pulse) begin
        dd_tp_cnt <= det_tp_cnt; dd_ra_cnt <= det_ra_cnt;
        dd_f1_cnt <= det_f1_cnt; dd_f2_cnt <= det_f2_cnt;
        dd_cs_cnt <= det_cs_cnt; dd_f3_cnt <= det_f3_cnt;
        dd_f4_cnt <= det_f4_cnt; dd_df_cnt <= det_df_cnt;
        dd_cx_cnt <= det_cx_cnt; dd_bk_cnt <= det_bk_cnt;
        dd_se_cnt <= det_se_cnt; dd_pq_cnt <= det_pq_cnt;
        dd_tp_voice <= det_tp_voice; dd_ra_voice <= det_ra_voice;
        dd_f1_voice <= det_f1_voice;
        dd_tp_exp <= det_tp_exp; dd_tp_seen <= det_tp_seen;
        dd_ra_accum <= det_ra_accum; dd_ra_cr <= det_ra_cr;
        dd_f1_reg <= det_f1_reg; dd_f1_bank <= det_f1_bank;
        dd_tp_frame <= det_tp_frame; dd_ra_frame <= det_ra_frame;
        dd_f1_frame <= det_f1_frame; dd_f2_frame <= det_f2_frame;
    end
end

always_ff @(posedge clk) begin
    if (rst) begin
        c_ticks <= '0; c_under <= '0; c_commit <= '0; c_hostwr <= '0;
        c_hostrd <= '0; c_iset <= '0; c_cesnd <= '0; c_p4req <= '0;
        c_g64 <= '0; c_g128 <= '0; c_g256 <= '0; c_latmaxf <= '0;
        t_under <= '0; t_p4 <= '0; t_tick <= '0;
        latmax_sticky <= '0; lat_last <= '0;
        c_lmin <= 16'sh7fff; c_lmax <= 16'sh8000;
        c_rmin <= 16'sh7fff; c_rmax <= 16'sh8000;
        last_irq_voice <= '0;
        disp_frame <= '0;
        disp_ticks <= '0; disp_under <= '0; disp_commit <= '0;
        disp_hostwr <= '0; disp_hostrd <= '0; disp_iset <= '0;
        disp_g64 <= '0; disp_g128 <= '0; disp_g256 <= '0; disp_latmaxf <= '0;
        disp_cesnd <= '0; disp_p4req <= '0;
        disp_undert <= '0; disp_p4tot <= '0; disp_ticktot <= '0; disp_run <= '0;
        disp_al <= '0; disp_ar <= '0;
        disp_lmin <= '0; disp_lmax <= '0; disp_rmin <= '0; disp_rmax <= '0;
        disp_av <= '0; disp_irqv <= '0; disp_pg <= '0; disp_irqn <= 1'b1;
    end else begin
        if (sample_tick) begin
            c_ticks <= c_ticks + 1'd1;
            t_tick  <= t_tick + 1'd1;
            if (audio_l < c_lmin) c_lmin <= audio_l;
            if (audio_l > c_lmax) c_lmax <= audio_l;
            if (audio_r < c_rmin) c_rmin <= audio_r;
            if (audio_r > c_rmax) c_rmax <= audio_r;
        end
        if (under_edge) begin
            c_under <= c_under + 1'd1;
            t_under <= t_under + 1'd1;
        end
        if (commit)      c_commit <= c_commit + 1'd1;
        if (hostwe_edge) c_hostwr <= c_hostwr + 1'd1;
        if (hostre_edge) c_hostrd <= c_hostrd + 1'd1;
        if (irq_set) begin
            c_iset <= c_iset + 1'd1;
            last_irq_voice <= irq_voice;
        end
        if (ce_snd) c_cesnd <= c_cesnd + 1'd1;
        if (p4_done) begin
            c_p4req <= c_p4req + 1'd1;
            t_p4    <= t_p4 + 1'd1;
            lat_last <= lat_now;
            if (lat_now > latmax_sticky) latmax_sticky <= lat_now;
            if (lat_now > c_latmaxf)     c_latmaxf <= lat_now;
            if (lat_now >= 16'd64)  c_g64  <= c_g64 + 1'd1;
            if (lat_now >= 16'd128) c_g128 <= c_g128 + 1'd1;
            if (lat_now >= 16'd256) c_g256 <= c_g256 + 1'd1;
        end

        if (frame_pulse) begin
            disp_frame  <= disp_frame + 1'd1;
            disp_ticks  <= c_ticks;    c_ticks  <= '0;
            disp_under  <= c_under;    c_under  <= '0;
            disp_commit <= c_commit;   c_commit <= '0;
            disp_hostwr <= c_hostwr;   c_hostwr <= '0;
            disp_hostrd <= c_hostrd;   c_hostrd <= '0;
            disp_iset   <= c_iset;     c_iset   <= '0;
            disp_cesnd  <= c_cesnd;    c_cesnd  <= '0;
            disp_p4req  <= c_p4req;    c_p4req  <= '0;
            disp_g64    <= c_g64;      c_g64    <= '0;
            disp_g128   <= c_g128;     c_g128   <= '0;
            disp_g256   <= c_g256;     c_g256   <= '0;
            disp_latmaxf<= c_latmaxf;  c_latmaxf<= '0;
            disp_lmin   <= c_lmin;     c_lmin   <= 16'sh7fff;
            disp_lmax   <= c_lmax;     c_lmax   <= 16'sh8000;
            disp_rmin   <= c_rmin;     c_rmin   <= 16'sh7fff;
            disp_rmax   <= c_rmax;     c_rmax   <= 16'sh8000;
            disp_undert <= t_under;
            disp_p4tot  <= t_p4;
            disp_ticktot<= t_tick;
            disp_run    <= run_mask;
            disp_al     <= audio_l;
            disp_ar     <= audio_r;
            disp_av     <= active_voices;
            disp_pg     <= current_page;
            disp_irqn   <= irq_n;
            disp_irqv   <= last_irq_voice;
        end
    end
end

// ---------------------------------------------------------------------------
// Host commit log: newest-first 12-entry shift chain, display copy latched
// per frame so a screenshot never shows a mid-shift mixture.
// ---------------------------------------------------------------------------
typedef struct packed {
    logic [6:0]  page;
    logic [3:0]  regn;
    logic [31:0] data;
} logent_t;
logent_t log_q [0:11];
logent_t disp_log [0:11];
always_ff @(posedge clk) begin
    if (rst) begin
        for (int i = 0; i < 12; i++) begin
            log_q[i] <= '0;
            disp_log[i] <= '0;
        end
    end else begin
        if (commit) begin
            log_q[0] <= {commit_page, commit_reg, commit_data};
            for (int i = 1; i < 12; i++) log_q[i] <= log_q[i-1];
        end
        if (frame_pulse)
            for (int i = 0; i < 12; i++) disp_log[i] <= log_q[i];
    end
end

// ---------------------------------------------------------------------------
// Text grid position. Cells are 4 px wide (hcnt[1:0] inside), 6 lines tall.
// Divide-by-6 via multiply: vcnt*683 >> 12 is exact for 0..261.
// ---------------------------------------------------------------------------
wire [6:0] tcol = hcnt[8:2];
wire [1:0] gx   = hcnt[1:0];
// Low 12 bits of the products are the discarded fixed-point fraction.
/* verilator lint_off UNUSEDSIGNAL */
wire [19:0] vprod = vcnt * 20'd683;
wire [19:0] vnprod = vnext * 20'd683;
/* verilator lint_on UNUSEDSIGNAL */
wire [5:0] trow  = vprod[17:12];
wire [2:0] tline = 3'(vcnt - 9'({trow, 1'b0}) - 9'({trow, 2'b00})); // vcnt-trow*6

// Prefetch next line's voice record during this line's blanking.
wire [8:0] vnext = vcnt + 9'd1;
wire [5:0] nrow = vnprod[17:12];
logic pf1, pf2;
logic [7:0]      vnum_r;
logic [REC_W-1:0] vrec;
always_ff @(posedge clk) begin
    pf1 <= 1'b0;
    pf2 <= pf1;
    if (ce_pixel && (hcnt == active_width)) begin
        if (nrow >= 6'd5 && nrow <= 6'd36) begin
            shadow_rd_addr <= 5'(nrow - 6'd5);
            pf1 <= 1'b1;
        end
    end
    if (pf2) begin
        vrec   <= shadow_q;
        vnum_r <= {3'd0, shadow_rd_addr};
    end
end

// ---------------------------------------------------------------------------
// Display-value wires, zero-padded to whole hex digits.
// ---------------------------------------------------------------------------
wire [31:0] fx_frame  = disp_frame;
wire [7:0]  fx_av     = {3'd0, disp_av};
wire [7:0]  fx_pg     = {1'd0, disp_pg};
wire [3:0]  fx_irqn   = {3'd0, disp_irqn};
wire [7:0]  fx_irqv   = {3'd0, disp_irqv};
wire [15:0] fx_iset   = disp_iset;
wire [15:0] fx_ticks  = disp_ticks;
wire [15:0] fx_underf = disp_under;
wire [31:0] fx_undert = disp_undert;
wire [23:0] fx_cesnd  = disp_cesnd;
wire [23:0] fx_p4req  = disp_p4req;
wire [15:0] fx_commitf= disp_commit;
wire [15:0] fx_hostwr = disp_hostwr;
wire [15:0] fx_hostrd = disp_hostrd;
wire [15:0] fx_latmax = latmax_sticky;
wire [15:0] fx_latmaxf= disp_latmaxf;
wire [15:0] fx_latlast= lat_last;
wire [15:0] fx_g64    = disp_g64;
wire [15:0] fx_g128   = disp_g128;
wire [15:0] fx_g256   = disp_g256;
wire [31:0] fx_p4tot  = disp_p4tot;
wire [15:0] fx_al     = disp_al;
wire [15:0] fx_ar     = disp_ar;
wire [15:0] fx_lmin   = disp_lmin;
wire [15:0] fx_lmax   = disp_lmax;
wire [15:0] fx_rmin   = disp_rmin;
wire [15:0] fx_rmax   = disp_rmax;
wire [31:0] fx_run    = disp_run;
wire [31:0] fx_ticktot= disp_ticktot;

// Detector panel display wires.
wire [7:0]  fx_dtpv = {3'd0, dd_tp_voice};
wire [7:0]  fx_drav = {3'd0, dd_ra_voice};
wire [7:0]  fx_df1v = {3'd0, dd_f1_voice};
wire [3:0]  fx_df1r = dd_f1_reg;
wire [3:0]  fx_df1b = {3'd0, dd_f1_bank};

wire [7:0]  fx_vn  = vnum_r;
wire [15:0] fx_vcr = vrec[201:186];
wire [19:0] fx_vfc = {3'd0, vrec[185:169]};
wire [31:0] fx_vac = vrec[168:137];
wire [31:0] fx_vsa = vrec[136:105];
wire [31:0] fx_vea = vrec[104:73];
wire [15:0] fx_vlv = vrec[72:57];
wire [15:0] fx_vrv = vrec[56:41];
wire [11:0] fx_vec = {3'd0, vrec[40:32]};
wire [15:0] fx_vk1 = vrec[31:16];
wire [15:0] fx_vk2 = vrec[15:0];

wire [7:0]  fx_log0p = {1'd0, disp_log[0].page};
wire [3:0]  fx_log0r = disp_log[0].regn;
wire [31:0] fx_log0d = disp_log[0].data;
wire [7:0]  fx_log1p = {1'd0, disp_log[1].page};
wire [3:0]  fx_log1r = disp_log[1].regn;
wire [31:0] fx_log1d = disp_log[1].data;
wire [7:0]  fx_log2p = {1'd0, disp_log[2].page};
wire [3:0]  fx_log2r = disp_log[2].regn;
wire [31:0] fx_log2d = disp_log[2].data;
wire [7:0]  fx_log3p = {1'd0, disp_log[3].page};
wire [3:0]  fx_log3r = disp_log[3].regn;
wire [31:0] fx_log3d = disp_log[3].data;
wire [7:0]  fx_log4p = {1'd0, disp_log[4].page};
wire [3:0]  fx_log4r = disp_log[4].regn;
wire [31:0] fx_log4d = disp_log[4].data;
wire [7:0]  fx_log5p = {1'd0, disp_log[5].page};
wire [3:0]  fx_log5r = disp_log[5].regn;
wire [31:0] fx_log5d = disp_log[5].data;
wire [7:0]  fx_log6p = {1'd0, disp_log[6].page};
wire [3:0]  fx_log6r = disp_log[6].regn;
wire [31:0] fx_log6d = disp_log[6].data;
wire [7:0]  fx_log7p = {1'd0, disp_log[7].page};
wire [3:0]  fx_log7r = disp_log[7].regn;
wire [31:0] fx_log7d = disp_log[7].data;
wire [7:0]  fx_log8p = {1'd0, disp_log[8].page};
wire [3:0]  fx_log8r = disp_log[8].regn;
wire [31:0] fx_log8d = disp_log[8].data;
wire [7:0]  fx_log9p = {1'd0, disp_log[9].page};
wire [3:0]  fx_log9r = disp_log[9].regn;
wire [31:0] fx_log9d = disp_log[9].data;
wire [7:0]  fx_log10p = {1'd0, disp_log[10].page};
wire [3:0]  fx_log10r = disp_log[10].regn;
wire [31:0] fx_log10d = disp_log[10].data;
wire [7:0]  fx_log11p = {1'd0, disp_log[11].page};
wire [3:0]  fx_log11r = disp_log[11].regn;
wire [31:0] fx_log11d = disp_log[11].data;

// ---------------------------------------------------------------------------
// Character select (generated).
// ---------------------------------------------------------------------------
logic [5:0] charcode;
always_comb begin
    charcode = 6'd16; // space
    if (trow >= 6'd5 && trow <= 6'd36) begin
            case (tcol)
                7'd0: charcode = {2'b00, fx_vn[7:4]};
                7'd1: charcode = {2'b00, fx_vn[3:0]};
                7'd3: charcode = {2'b00, fx_vcr[15:12]};
                7'd4: charcode = {2'b00, fx_vcr[11:8]};
                7'd5: charcode = {2'b00, fx_vcr[7:4]};
                7'd6: charcode = {2'b00, fx_vcr[3:0]};
                7'd8: charcode = {2'b00, fx_vfc[19:16]};
                7'd9: charcode = {2'b00, fx_vfc[15:12]};
                7'd10: charcode = {2'b00, fx_vfc[11:8]};
                7'd11: charcode = {2'b00, fx_vfc[7:4]};
                7'd12: charcode = {2'b00, fx_vfc[3:0]};
                7'd14: charcode = {2'b00, fx_vac[31:28]};
                7'd15: charcode = {2'b00, fx_vac[27:24]};
                7'd16: charcode = {2'b00, fx_vac[23:20]};
                7'd17: charcode = {2'b00, fx_vac[19:16]};
                7'd18: charcode = {2'b00, fx_vac[15:12]};
                7'd19: charcode = {2'b00, fx_vac[11:8]};
                7'd20: charcode = {2'b00, fx_vac[7:4]};
                7'd21: charcode = {2'b00, fx_vac[3:0]};
                7'd23: charcode = {2'b00, fx_vsa[31:28]};
                7'd24: charcode = {2'b00, fx_vsa[27:24]};
                7'd25: charcode = {2'b00, fx_vsa[23:20]};
                7'd26: charcode = {2'b00, fx_vsa[19:16]};
                7'd27: charcode = {2'b00, fx_vsa[15:12]};
                7'd28: charcode = {2'b00, fx_vsa[11:8]};
                7'd29: charcode = {2'b00, fx_vsa[7:4]};
                7'd30: charcode = {2'b00, fx_vsa[3:0]};
                7'd32: charcode = {2'b00, fx_vea[31:28]};
                7'd33: charcode = {2'b00, fx_vea[27:24]};
                7'd34: charcode = {2'b00, fx_vea[23:20]};
                7'd35: charcode = {2'b00, fx_vea[19:16]};
                7'd36: charcode = {2'b00, fx_vea[15:12]};
                7'd37: charcode = {2'b00, fx_vea[11:8]};
                7'd38: charcode = {2'b00, fx_vea[7:4]};
                7'd39: charcode = {2'b00, fx_vea[3:0]};
                7'd41: charcode = {2'b00, fx_vlv[15:12]};
                7'd42: charcode = {2'b00, fx_vlv[11:8]};
                7'd43: charcode = {2'b00, fx_vlv[7:4]};
                7'd44: charcode = {2'b00, fx_vlv[3:0]};
                7'd46: charcode = {2'b00, fx_vrv[15:12]};
                7'd47: charcode = {2'b00, fx_vrv[11:8]};
                7'd48: charcode = {2'b00, fx_vrv[7:4]};
                7'd49: charcode = {2'b00, fx_vrv[3:0]};
                7'd51: charcode = {2'b00, fx_vec[11:8]};
                7'd52: charcode = {2'b00, fx_vec[7:4]};
                7'd53: charcode = {2'b00, fx_vec[3:0]};
                7'd55: charcode = {2'b00, fx_vk1[15:12]};
                7'd56: charcode = {2'b00, fx_vk1[11:8]};
                7'd57: charcode = {2'b00, fx_vk1[7:4]};
                7'd58: charcode = {2'b00, fx_vk1[3:0]};
                7'd60: charcode = {2'b00, fx_vk2[15:12]};
                7'd61: charcode = {2'b00, fx_vk2[11:8]};
                7'd62: charcode = {2'b00, fx_vk2[7:4]};
                7'd63: charcode = {2'b00, fx_vk2[3:0]};
                default: ;
            endcase
            // Detector panel, columns 66+ alongside the voice table.
            if (tcol >= 7'd66) begin
                unique case (trow)
                    6'd5: case (tcol)  // DET
                        7'd66: charcode = 6'd13;
                        7'd67: charcode = 6'd14;
                        7'd68: charcode = 6'd34;
                        default: ;
                    endcase
                    6'd6: case (tcol)  // TP:cccc
                        7'd66: charcode = 6'd34;
                        7'd67: charcode = 6'd30;
                        7'd68: charcode = 6'd17;
                        7'd69: charcode = {2'b00, dd_tp_cnt[15:12]};
                        7'd70: charcode = {2'b00, dd_tp_cnt[11:8]};
                        7'd71: charcode = {2'b00, dd_tp_cnt[7:4]};
                        7'd72: charcode = {2'b00, dd_tp_cnt[3:0]};
                        default: ;
                    endcase
                    6'd7: case (tcol)  // V:vv
                        7'd66: charcode = 6'd36;
                        7'd67: charcode = 6'd17;
                        7'd68: charcode = {2'b00, fx_dtpv[7:4]};
                        7'd69: charcode = {2'b00, fx_dtpv[3:0]};
                        default: ;
                    endcase
                    6'd8: case (tcol)  // E:eeeeeeee
                        7'd66: charcode = 6'd14;
                        7'd67: charcode = 6'd17;
                        7'd68: charcode = {2'b00, dd_tp_exp[31:28]};
                        7'd69: charcode = {2'b00, dd_tp_exp[27:24]};
                        7'd70: charcode = {2'b00, dd_tp_exp[23:20]};
                        7'd71: charcode = {2'b00, dd_tp_exp[19:16]};
                        7'd72: charcode = {2'b00, dd_tp_exp[15:12]};
                        7'd73: charcode = {2'b00, dd_tp_exp[11:8]};
                        7'd74: charcode = {2'b00, dd_tp_exp[7:4]};
                        7'd75: charcode = {2'b00, dd_tp_exp[3:0]};
                        default: ;
                    endcase
                    6'd9: case (tcol)  // S:ssssssss
                        7'd66: charcode = 6'd33;
                        7'd67: charcode = 6'd17;
                        7'd68: charcode = {2'b00, dd_tp_seen[31:28]};
                        7'd69: charcode = {2'b00, dd_tp_seen[27:24]};
                        7'd70: charcode = {2'b00, dd_tp_seen[23:20]};
                        7'd71: charcode = {2'b00, dd_tp_seen[19:16]};
                        7'd72: charcode = {2'b00, dd_tp_seen[15:12]};
                        7'd73: charcode = {2'b00, dd_tp_seen[11:8]};
                        7'd74: charcode = {2'b00, dd_tp_seen[7:4]};
                        7'd75: charcode = {2'b00, dd_tp_seen[3:0]};
                        default: ;
                    endcase
                    6'd10: case (tcol) // TF:ffff
                        7'd66: charcode = 6'd34;
                        7'd67: charcode = 6'd15;
                        7'd68: charcode = 6'd17;
                        7'd69: charcode = {2'b00, dd_tp_frame[15:12]};
                        7'd70: charcode = {2'b00, dd_tp_frame[11:8]};
                        7'd71: charcode = {2'b00, dd_tp_frame[7:4]};
                        7'd72: charcode = {2'b00, dd_tp_frame[3:0]};
                        default: ;
                    endcase
                    6'd11: case (tcol) // RA:cccc
                        7'd66: charcode = 6'd32;
                        7'd67: charcode = 6'd10;
                        7'd68: charcode = 6'd17;
                        7'd69: charcode = {2'b00, dd_ra_cnt[15:12]};
                        7'd70: charcode = {2'b00, dd_ra_cnt[11:8]};
                        7'd71: charcode = {2'b00, dd_ra_cnt[7:4]};
                        7'd72: charcode = {2'b00, dd_ra_cnt[3:0]};
                        default: ;
                    endcase
                    6'd12: case (tcol) // V:vv
                        7'd66: charcode = 6'd36;
                        7'd67: charcode = 6'd17;
                        7'd68: charcode = {2'b00, fx_drav[7:4]};
                        7'd69: charcode = {2'b00, fx_drav[3:0]};
                        default: ;
                    endcase
                    6'd13: case (tcol) // C:cccc
                        7'd66: charcode = 6'd12;
                        7'd67: charcode = 6'd17;
                        7'd68: charcode = {2'b00, dd_ra_cr[15:12]};
                        7'd69: charcode = {2'b00, dd_ra_cr[11:8]};
                        7'd70: charcode = {2'b00, dd_ra_cr[7:4]};
                        7'd71: charcode = {2'b00, dd_ra_cr[3:0]};
                        default: ;
                    endcase
                    6'd14: case (tcol) // A:aaaaaaaa
                        7'd66: charcode = 6'd10;
                        7'd67: charcode = 6'd17;
                        7'd68: charcode = {2'b00, dd_ra_accum[31:28]};
                        7'd69: charcode = {2'b00, dd_ra_accum[27:24]};
                        7'd70: charcode = {2'b00, dd_ra_accum[23:20]};
                        7'd71: charcode = {2'b00, dd_ra_accum[19:16]};
                        7'd72: charcode = {2'b00, dd_ra_accum[15:12]};
                        7'd73: charcode = {2'b00, dd_ra_accum[11:8]};
                        7'd74: charcode = {2'b00, dd_ra_accum[7:4]};
                        7'd75: charcode = {2'b00, dd_ra_accum[3:0]};
                        default: ;
                    endcase
                    6'd15: case (tcol) // RF:ffff
                        7'd66: charcode = 6'd32;
                        7'd67: charcode = 6'd15;
                        7'd68: charcode = 6'd17;
                        7'd69: charcode = {2'b00, dd_ra_frame[15:12]};
                        7'd70: charcode = {2'b00, dd_ra_frame[11:8]};
                        7'd71: charcode = {2'b00, dd_ra_frame[7:4]};
                        7'd72: charcode = {2'b00, dd_ra_frame[3:0]};
                        default: ;
                    endcase
                    6'd16: case (tcol) // F1:cccc
                        7'd66: charcode = 6'd15;
                        7'd67: charcode = 6'd1;
                        7'd68: charcode = 6'd17;
                        7'd69: charcode = {2'b00, dd_f1_cnt[15:12]};
                        7'd70: charcode = {2'b00, dd_f1_cnt[11:8]};
                        7'd71: charcode = {2'b00, dd_f1_cnt[7:4]};
                        7'd72: charcode = {2'b00, dd_f1_cnt[3:0]};
                        default: ;
                    endcase
                    6'd17: case (tcol) // V:vv R:r B:b
                        7'd66: charcode = 6'd36;
                        7'd67: charcode = 6'd17;
                        7'd68: charcode = {2'b00, fx_df1v[7:4]};
                        7'd69: charcode = {2'b00, fx_df1v[3:0]};
                        7'd71: charcode = 6'd32;
                        7'd72: charcode = 6'd17;
                        7'd73: charcode = {2'b00, fx_df1r};
                        7'd75: charcode = 6'd11;
                        7'd76: charcode = 6'd17;
                        7'd77: charcode = {2'b00, fx_df1b};
                        default: ;
                    endcase
                    6'd18: case (tcol) // F2:cccc
                        7'd66: charcode = 6'd15;
                        7'd67: charcode = 6'd2;
                        7'd68: charcode = 6'd17;
                        7'd69: charcode = {2'b00, dd_f2_cnt[15:12]};
                        7'd70: charcode = {2'b00, dd_f2_cnt[11:8]};
                        7'd71: charcode = {2'b00, dd_f2_cnt[7:4]};
                        7'd72: charcode = {2'b00, dd_f2_cnt[3:0]};
                        default: ;
                    endcase
                    6'd19: case (tcol) // 2F:ffff
                        7'd66: charcode = 6'd2;
                        7'd67: charcode = 6'd15;
                        7'd68: charcode = 6'd17;
                        7'd69: charcode = {2'b00, dd_f2_frame[15:12]};
                        7'd70: charcode = {2'b00, dd_f2_frame[11:8]};
                        7'd71: charcode = {2'b00, dd_f2_frame[7:4]};
                        7'd72: charcode = {2'b00, dd_f2_frame[3:0]};
                        default: ;
                    endcase
                    6'd20: case (tcol) // CS:cccc
                        7'd66: charcode = 6'd12;
                        7'd67: charcode = 6'd33;
                        7'd68: charcode = 6'd17;
                        7'd69: charcode = {2'b00, dd_cs_cnt[15:12]};
                        7'd70: charcode = {2'b00, dd_cs_cnt[11:8]};
                        7'd71: charcode = {2'b00, dd_cs_cnt[7:4]};
                        7'd72: charcode = {2'b00, dd_cs_cnt[3:0]};
                        default: ;
                    endcase
                    6'd21: case (tcol) // F3:cccc
                        7'd66: charcode = 6'd15;
                        7'd67: charcode = 6'd3;
                        7'd68: charcode = 6'd17;
                        7'd69: charcode = {2'b00, dd_f3_cnt[15:12]};
                        7'd70: charcode = {2'b00, dd_f3_cnt[11:8]};
                        7'd71: charcode = {2'b00, dd_f3_cnt[7:4]};
                        7'd72: charcode = {2'b00, dd_f3_cnt[3:0]};
                        default: ;
                    endcase
                    6'd22: case (tcol) // F4:cccc
                        7'd66: charcode = 6'd15;
                        7'd67: charcode = 6'd4;
                        7'd68: charcode = 6'd17;
                        7'd69: charcode = {2'b00, dd_f4_cnt[15:12]};
                        7'd70: charcode = {2'b00, dd_f4_cnt[11:8]};
                        7'd71: charcode = {2'b00, dd_f4_cnt[7:4]};
                        7'd72: charcode = {2'b00, dd_f4_cnt[3:0]};
                        default: ;
                    endcase
                    6'd23: case (tcol) // DF:cccc
                        7'd66: charcode = 6'd13;
                        7'd67: charcode = 6'd15;
                        7'd68: charcode = 6'd17;
                        7'd69: charcode = {2'b00, dd_df_cnt[15:12]};
                        7'd70: charcode = {2'b00, dd_df_cnt[11:8]};
                        7'd71: charcode = {2'b00, dd_df_cnt[7:4]};
                        7'd72: charcode = {2'b00, dd_df_cnt[3:0]};
                        default: ;
                    endcase
                    6'd24: case (tcol) // CX:cccc
                        7'd66: charcode = 6'd12;
                        7'd67: charcode = 6'd38;
                        7'd68: charcode = 6'd17;
                        7'd69: charcode = {2'b00, dd_cx_cnt[15:12]};
                        7'd70: charcode = {2'b00, dd_cx_cnt[11:8]};
                        7'd71: charcode = {2'b00, dd_cx_cnt[7:4]};
                        7'd72: charcode = {2'b00, dd_cx_cnt[3:0]};
                        default: ;
                    endcase
                    6'd25: case (tcol) // BK:cccc
                        7'd66: charcode = 6'd11;
                        7'd67: charcode = 6'd26;
                        7'd68: charcode = 6'd17;
                        7'd69: charcode = {2'b00, dd_bk_cnt[15:12]};
                        7'd70: charcode = {2'b00, dd_bk_cnt[11:8]};
                        7'd71: charcode = {2'b00, dd_bk_cnt[7:4]};
                        7'd72: charcode = {2'b00, dd_bk_cnt[3:0]};
                        default: ;
                    endcase
                    6'd26: case (tcol) // SE:cccc
                        7'd66: charcode = 6'd33;
                        7'd67: charcode = 6'd14;
                        7'd68: charcode = 6'd17;
                        7'd69: charcode = {2'b00, dd_se_cnt[15:12]};
                        7'd70: charcode = {2'b00, dd_se_cnt[11:8]};
                        7'd71: charcode = {2'b00, dd_se_cnt[7:4]};
                        7'd72: charcode = {2'b00, dd_se_cnt[3:0]};
                        default: ;
                    endcase
                    6'd27: case (tcol) // PQ:cccc
                        7'd66: charcode = 6'd30;
                        7'd67: charcode = 6'd31;
                        7'd68: charcode = 6'd17;
                        7'd69: charcode = {2'b00, dd_pq_cnt[15:12]};
                        7'd70: charcode = {2'b00, dd_pq_cnt[11:8]};
                        7'd71: charcode = {2'b00, dd_pq_cnt[7:4]};
                        7'd72: charcode = {2'b00, dd_pq_cnt[3:0]};
                        default: ;
                    endcase
                    default: ;
                endcase
            end
    end else begin
        case (trow)
            6'd0: begin
                case (tcol)
                    7'd0: charcode = 6'd33;
                    7'd1: charcode = 6'd33;
                    7'd2: charcode = 6'd36;
                    7'd4: charcode = 6'd10;
                    7'd5: charcode = 6'd35;
                    7'd6: charcode = 6'd13;
                    7'd7: charcode = 6'd25;
                    7'd8: charcode = 6'd0;
                    7'd10: charcode = 6'd13;
                    7'd11: charcode = 6'd14;
                    7'd12: charcode = 6'd11;
                    7'd13: charcode = 6'd35;
                    7'd14: charcode = 6'd23;
                    7'd16: charcode = 6'd15;
                    7'd17: charcode = 6'd17;
                    7'd18: charcode = {2'b00, fx_frame[31:28]};
                    7'd19: charcode = {2'b00, fx_frame[27:24]};
                    7'd20: charcode = {2'b00, fx_frame[23:20]};
                    7'd21: charcode = {2'b00, fx_frame[19:16]};
                    7'd22: charcode = {2'b00, fx_frame[15:12]};
                    7'd23: charcode = {2'b00, fx_frame[11:8]};
                    7'd24: charcode = {2'b00, fx_frame[7:4]};
                    7'd25: charcode = {2'b00, fx_frame[3:0]};
                    7'd27: charcode = 6'd10;
                    7'd28: charcode = 6'd36;
                    7'd29: charcode = 6'd17;
                    7'd30: charcode = {2'b00, fx_av[7:4]};
                    7'd31: charcode = {2'b00, fx_av[3:0]};
                    7'd33: charcode = 6'd30;
                    7'd34: charcode = 6'd23;
                    7'd35: charcode = 6'd17;
                    7'd36: charcode = {2'b00, fx_pg[7:4]};
                    7'd37: charcode = {2'b00, fx_pg[3:0]};
                    7'd39: charcode = 6'd25;
                    7'd40: charcode = 6'd29;
                    7'd41: charcode = 6'd17;
                    7'd42: charcode = {2'b00, fx_irqn[3:0]};
                    7'd44: charcode = 6'd25;
                    7'd45: charcode = 6'd36;
                    7'd46: charcode = 6'd17;
                    7'd47: charcode = {2'b00, fx_irqv[7:4]};
                    7'd48: charcode = {2'b00, fx_irqv[3:0]};
                    7'd50: charcode = 6'd25;
                    7'd51: charcode = 6'd33;
                    7'd52: charcode = 6'd17;
                    7'd53: charcode = {2'b00, fx_iset[15:12]};
                    7'd54: charcode = {2'b00, fx_iset[11:8]};
                    7'd55: charcode = {2'b00, fx_iset[7:4]};
                    7'd56: charcode = {2'b00, fx_iset[3:0]};
                    7'd58: charcode = 6'd34;
                    7'd59: charcode = 6'd26;
                    7'd60: charcode = 6'd17;
                    7'd61: charcode = {2'b00, fx_ticks[15:12]};
                    7'd62: charcode = {2'b00, fx_ticks[11:8]};
                    7'd63: charcode = {2'b00, fx_ticks[7:4]};
                    7'd64: charcode = {2'b00, fx_ticks[3:0]};
                    default: ;
                endcase
            end
            6'd1: begin
                case (tcol)
                    7'd0: charcode = 6'd35;
                    7'd1: charcode = 6'd15;
                    7'd2: charcode = 6'd17;
                    7'd3: charcode = {2'b00, fx_underf[15:12]};
                    7'd4: charcode = {2'b00, fx_underf[11:8]};
                    7'd5: charcode = {2'b00, fx_underf[7:4]};
                    7'd6: charcode = {2'b00, fx_underf[3:0]};
                    7'd8: charcode = 6'd35;
                    7'd9: charcode = 6'd34;
                    7'd10: charcode = 6'd17;
                    7'd11: charcode = {2'b00, fx_undert[31:28]};
                    7'd12: charcode = {2'b00, fx_undert[27:24]};
                    7'd13: charcode = {2'b00, fx_undert[23:20]};
                    7'd14: charcode = {2'b00, fx_undert[19:16]};
                    7'd15: charcode = {2'b00, fx_undert[15:12]};
                    7'd16: charcode = {2'b00, fx_undert[11:8]};
                    7'd17: charcode = {2'b00, fx_undert[7:4]};
                    7'd18: charcode = {2'b00, fx_undert[3:0]};
                    7'd20: charcode = 6'd12;
                    7'd21: charcode = 6'd14;
                    7'd22: charcode = 6'd17;
                    7'd23: charcode = {2'b00, fx_cesnd[23:20]};
                    7'd24: charcode = {2'b00, fx_cesnd[19:16]};
                    7'd25: charcode = {2'b00, fx_cesnd[15:12]};
                    7'd26: charcode = {2'b00, fx_cesnd[11:8]};
                    7'd27: charcode = {2'b00, fx_cesnd[7:4]};
                    7'd28: charcode = {2'b00, fx_cesnd[3:0]};
                    7'd30: charcode = 6'd30;
                    7'd31: charcode = 6'd4;
                    7'd32: charcode = 6'd17;
                    7'd33: charcode = {2'b00, fx_p4req[23:20]};
                    7'd34: charcode = {2'b00, fx_p4req[19:16]};
                    7'd35: charcode = {2'b00, fx_p4req[15:12]};
                    7'd36: charcode = {2'b00, fx_p4req[11:8]};
                    7'd37: charcode = {2'b00, fx_p4req[7:4]};
                    7'd38: charcode = {2'b00, fx_p4req[3:0]};
                    7'd40: charcode = 6'd12;
                    7'd41: charcode = 6'd28;
                    7'd42: charcode = 6'd17;
                    7'd43: charcode = {2'b00, fx_commitf[15:12]};
                    7'd44: charcode = {2'b00, fx_commitf[11:8]};
                    7'd45: charcode = {2'b00, fx_commitf[7:4]};
                    7'd46: charcode = {2'b00, fx_commitf[3:0]};
                    7'd48: charcode = 6'd37;
                    7'd49: charcode = 6'd32;
                    7'd50: charcode = 6'd17;
                    7'd51: charcode = {2'b00, fx_hostwr[15:12]};
                    7'd52: charcode = {2'b00, fx_hostwr[11:8]};
                    7'd53: charcode = {2'b00, fx_hostwr[7:4]};
                    7'd54: charcode = {2'b00, fx_hostwr[3:0]};
                    7'd56: charcode = 6'd32;
                    7'd57: charcode = 6'd13;
                    7'd58: charcode = 6'd17;
                    7'd59: charcode = {2'b00, fx_hostrd[15:12]};
                    7'd60: charcode = {2'b00, fx_hostrd[11:8]};
                    7'd61: charcode = {2'b00, fx_hostrd[7:4]};
                    7'd62: charcode = {2'b00, fx_hostrd[3:0]};
                    default: ;
                endcase
            end
            6'd2: begin
                case (tcol)
                    7'd0: charcode = 6'd30;
                    7'd1: charcode = 6'd4;
                    7'd2: charcode = 6'd27;
                    7'd3: charcode = 6'd10;
                    7'd4: charcode = 6'd34;
                    7'd6: charcode = 6'd28;
                    7'd7: charcode = 6'd38;
                    7'd8: charcode = 6'd17;
                    7'd9: charcode = {2'b00, fx_latmax[15:12]};
                    7'd10: charcode = {2'b00, fx_latmax[11:8]};
                    7'd11: charcode = {2'b00, fx_latmax[7:4]};
                    7'd12: charcode = {2'b00, fx_latmax[3:0]};
                    7'd14: charcode = 6'd28;
                    7'd15: charcode = 6'd15;
                    7'd16: charcode = 6'd17;
                    7'd17: charcode = {2'b00, fx_latmaxf[15:12]};
                    7'd18: charcode = {2'b00, fx_latmaxf[11:8]};
                    7'd19: charcode = {2'b00, fx_latmaxf[7:4]};
                    7'd20: charcode = {2'b00, fx_latmaxf[3:0]};
                    7'd22: charcode = 6'd27;
                    7'd23: charcode = 6'd27;
                    7'd24: charcode = 6'd17;
                    7'd25: charcode = {2'b00, fx_latlast[15:12]};
                    7'd26: charcode = {2'b00, fx_latlast[11:8]};
                    7'd27: charcode = {2'b00, fx_latlast[7:4]};
                    7'd28: charcode = {2'b00, fx_latlast[3:0]};
                    7'd30: charcode = 6'd23;
                    7'd31: charcode = 6'd6;
                    7'd32: charcode = 6'd4;
                    7'd33: charcode = 6'd17;
                    7'd34: charcode = {2'b00, fx_g64[15:12]};
                    7'd35: charcode = {2'b00, fx_g64[11:8]};
                    7'd36: charcode = {2'b00, fx_g64[7:4]};
                    7'd37: charcode = {2'b00, fx_g64[3:0]};
                    7'd39: charcode = 6'd23;
                    7'd40: charcode = 6'd1;
                    7'd41: charcode = 6'd2;
                    7'd42: charcode = 6'd8;
                    7'd43: charcode = 6'd17;
                    7'd44: charcode = {2'b00, fx_g128[15:12]};
                    7'd45: charcode = {2'b00, fx_g128[11:8]};
                    7'd46: charcode = {2'b00, fx_g128[7:4]};
                    7'd47: charcode = {2'b00, fx_g128[3:0]};
                    7'd49: charcode = 6'd23;
                    7'd50: charcode = 6'd2;
                    7'd51: charcode = 6'd5;
                    7'd52: charcode = 6'd6;
                    7'd53: charcode = 6'd17;
                    7'd54: charcode = {2'b00, fx_g256[15:12]};
                    7'd55: charcode = {2'b00, fx_g256[11:8]};
                    7'd56: charcode = {2'b00, fx_g256[7:4]};
                    7'd57: charcode = {2'b00, fx_g256[3:0]};
                    7'd59: charcode = 6'd30;
                    7'd60: charcode = 6'd34;
                    7'd61: charcode = 6'd17;
                    7'd62: charcode = {2'b00, fx_p4tot[31:28]};
                    7'd63: charcode = {2'b00, fx_p4tot[27:24]};
                    7'd64: charcode = {2'b00, fx_p4tot[23:20]};
                    7'd65: charcode = {2'b00, fx_p4tot[19:16]};
                    7'd66: charcode = {2'b00, fx_p4tot[15:12]};
                    7'd67: charcode = {2'b00, fx_p4tot[11:8]};
                    7'd68: charcode = {2'b00, fx_p4tot[7:4]};
                    7'd69: charcode = {2'b00, fx_p4tot[3:0]};
                    default: ;
                endcase
            end
            6'd3: begin
                case (tcol)
                    7'd0: charcode = 6'd27;
                    7'd1: charcode = 6'd17;
                    7'd2: charcode = {2'b00, fx_al[15:12]};
                    7'd3: charcode = {2'b00, fx_al[11:8]};
                    7'd4: charcode = {2'b00, fx_al[7:4]};
                    7'd5: charcode = {2'b00, fx_al[3:0]};
                    7'd7: charcode = 6'd32;
                    7'd8: charcode = 6'd17;
                    7'd9: charcode = {2'b00, fx_ar[15:12]};
                    7'd10: charcode = {2'b00, fx_ar[11:8]};
                    7'd11: charcode = {2'b00, fx_ar[7:4]};
                    7'd12: charcode = {2'b00, fx_ar[3:0]};
                    7'd14: charcode = 6'd27;
                    7'd15: charcode = 6'd28;
                    7'd16: charcode = 6'd25;
                    7'd17: charcode = 6'd17;
                    7'd18: charcode = {2'b00, fx_lmin[15:12]};
                    7'd19: charcode = {2'b00, fx_lmin[11:8]};
                    7'd20: charcode = {2'b00, fx_lmin[7:4]};
                    7'd21: charcode = {2'b00, fx_lmin[3:0]};
                    7'd23: charcode = 6'd27;
                    7'd24: charcode = 6'd28;
                    7'd25: charcode = 6'd10;
                    7'd26: charcode = 6'd17;
                    7'd27: charcode = {2'b00, fx_lmax[15:12]};
                    7'd28: charcode = {2'b00, fx_lmax[11:8]};
                    7'd29: charcode = {2'b00, fx_lmax[7:4]};
                    7'd30: charcode = {2'b00, fx_lmax[3:0]};
                    7'd32: charcode = 6'd32;
                    7'd33: charcode = 6'd28;
                    7'd34: charcode = 6'd25;
                    7'd35: charcode = 6'd17;
                    7'd36: charcode = {2'b00, fx_rmin[15:12]};
                    7'd37: charcode = {2'b00, fx_rmin[11:8]};
                    7'd38: charcode = {2'b00, fx_rmin[7:4]};
                    7'd39: charcode = {2'b00, fx_rmin[3:0]};
                    7'd41: charcode = 6'd32;
                    7'd42: charcode = 6'd28;
                    7'd43: charcode = 6'd10;
                    7'd44: charcode = 6'd17;
                    7'd45: charcode = {2'b00, fx_rmax[15:12]};
                    7'd46: charcode = {2'b00, fx_rmax[11:8]};
                    7'd47: charcode = {2'b00, fx_rmax[7:4]};
                    7'd48: charcode = {2'b00, fx_rmax[3:0]};
                    7'd50: charcode = 6'd32;
                    7'd51: charcode = 6'd35;
                    7'd52: charcode = 6'd29;
                    7'd53: charcode = 6'd17;
                    7'd54: charcode = {2'b00, fx_run[31:28]};
                    7'd55: charcode = {2'b00, fx_run[27:24]};
                    7'd56: charcode = {2'b00, fx_run[23:20]};
                    7'd57: charcode = {2'b00, fx_run[19:16]};
                    7'd58: charcode = {2'b00, fx_run[15:12]};
                    7'd59: charcode = {2'b00, fx_run[11:8]};
                    7'd60: charcode = {2'b00, fx_run[7:4]};
                    7'd61: charcode = {2'b00, fx_run[3:0]};
                    7'd63: charcode = 6'd34;
                    7'd64: charcode = 6'd34;
                    7'd65: charcode = 6'd17;
                    7'd66: charcode = {2'b00, fx_ticktot[31:28]};
                    7'd67: charcode = {2'b00, fx_ticktot[27:24]};
                    7'd68: charcode = {2'b00, fx_ticktot[23:20]};
                    7'd69: charcode = {2'b00, fx_ticktot[19:16]};
                    7'd70: charcode = {2'b00, fx_ticktot[15:12]};
                    7'd71: charcode = {2'b00, fx_ticktot[11:8]};
                    7'd72: charcode = {2'b00, fx_ticktot[7:4]};
                    7'd73: charcode = {2'b00, fx_ticktot[3:0]};
                    default: ;
                endcase
            end
            6'd4: begin
                case (tcol)
                    7'd0: charcode = 6'd36;
                    7'd1: charcode = 6'd12;
                    7'd3: charcode = 6'd12;
                    7'd4: charcode = 6'd32;
                    7'd8: charcode = 6'd15;
                    7'd9: charcode = 6'd12;
                    7'd14: charcode = 6'd10;
                    7'd15: charcode = 6'd12;
                    7'd16: charcode = 6'd12;
                    7'd17: charcode = 6'd35;
                    7'd18: charcode = 6'd28;
                    7'd23: charcode = 6'd33;
                    7'd24: charcode = 6'd34;
                    7'd25: charcode = 6'd10;
                    7'd26: charcode = 6'd32;
                    7'd27: charcode = 6'd34;
                    7'd32: charcode = 6'd14;
                    7'd33: charcode = 6'd29;
                    7'd34: charcode = 6'd13;
                    7'd41: charcode = 6'd27;
                    7'd42: charcode = 6'd36;
                    7'd43: charcode = 6'd0;
                    7'd44: charcode = 6'd27;
                    7'd46: charcode = 6'd32;
                    7'd47: charcode = 6'd36;
                    7'd48: charcode = 6'd0;
                    7'd49: charcode = 6'd27;
                    7'd51: charcode = 6'd14;
                    7'd52: charcode = 6'd12;
                    7'd55: charcode = 6'd26;
                    7'd56: charcode = 6'd1;
                    7'd60: charcode = 6'd26;
                    7'd61: charcode = 6'd2;
                    default: ;
                endcase
            end
            6'd37: begin
                case (tcol)
                    7'd0: charcode = 6'd12;
                    7'd1: charcode = 6'd0;
                    7'd2: charcode = 6'd28;
                    7'd3: charcode = 6'd28;
                    7'd4: charcode = 6'd25;
                    7'd5: charcode = 6'd34;
                    7'd7: charcode = 6'd27;
                    7'd8: charcode = 6'd0;
                    7'd9: charcode = 6'd23;
                    7'd11: charcode = 6'd30;
                    7'd12: charcode = 6'd23;
                    7'd13: charcode = 6'd19;
                    7'd14: charcode = 6'd32;
                    7'd15: charcode = 6'd23;
                    7'd16: charcode = 6'd19;
                    7'd17: charcode = 6'd13;
                    7'd18: charcode = 6'd10;
                    7'd19: charcode = 6'd34;
                    7'd20: charcode = 6'd10;
                    7'd22: charcode = 6'd29;
                    7'd23: charcode = 6'd14;
                    7'd24: charcode = 6'd37;
                    7'd25: charcode = 6'd20;
                    7'd26: charcode = 6'd0;
                    7'd27: charcode = 6'd27;
                    7'd28: charcode = 6'd13;
                    default: ;
                endcase
            end
            6'd38: begin
                case (tcol)
                    7'd0: charcode = {2'b00, fx_log0p[7:4]};
                    7'd1: charcode = {2'b00, fx_log0p[3:0]};
                    7'd2: charcode = 6'd19;
                    7'd3: charcode = {2'b00, fx_log0r[3:0]};
                    7'd4: charcode = 6'd19;
                    7'd5: charcode = {2'b00, fx_log0d[31:28]};
                    7'd6: charcode = {2'b00, fx_log0d[27:24]};
                    7'd7: charcode = {2'b00, fx_log0d[23:20]};
                    7'd8: charcode = {2'b00, fx_log0d[19:16]};
                    7'd9: charcode = {2'b00, fx_log0d[15:12]};
                    7'd10: charcode = {2'b00, fx_log0d[11:8]};
                    7'd11: charcode = {2'b00, fx_log0d[7:4]};
                    7'd12: charcode = {2'b00, fx_log0d[3:0]};
                    7'd14: charcode = {2'b00, fx_log1p[7:4]};
                    7'd15: charcode = {2'b00, fx_log1p[3:0]};
                    7'd16: charcode = 6'd19;
                    7'd17: charcode = {2'b00, fx_log1r[3:0]};
                    7'd18: charcode = 6'd19;
                    7'd19: charcode = {2'b00, fx_log1d[31:28]};
                    7'd20: charcode = {2'b00, fx_log1d[27:24]};
                    7'd21: charcode = {2'b00, fx_log1d[23:20]};
                    7'd22: charcode = {2'b00, fx_log1d[19:16]};
                    7'd23: charcode = {2'b00, fx_log1d[15:12]};
                    7'd24: charcode = {2'b00, fx_log1d[11:8]};
                    7'd25: charcode = {2'b00, fx_log1d[7:4]};
                    7'd26: charcode = {2'b00, fx_log1d[3:0]};
                    7'd28: charcode = {2'b00, fx_log2p[7:4]};
                    7'd29: charcode = {2'b00, fx_log2p[3:0]};
                    7'd30: charcode = 6'd19;
                    7'd31: charcode = {2'b00, fx_log2r[3:0]};
                    7'd32: charcode = 6'd19;
                    7'd33: charcode = {2'b00, fx_log2d[31:28]};
                    7'd34: charcode = {2'b00, fx_log2d[27:24]};
                    7'd35: charcode = {2'b00, fx_log2d[23:20]};
                    7'd36: charcode = {2'b00, fx_log2d[19:16]};
                    7'd37: charcode = {2'b00, fx_log2d[15:12]};
                    7'd38: charcode = {2'b00, fx_log2d[11:8]};
                    7'd39: charcode = {2'b00, fx_log2d[7:4]};
                    7'd40: charcode = {2'b00, fx_log2d[3:0]};
                    7'd42: charcode = {2'b00, fx_log3p[7:4]};
                    7'd43: charcode = {2'b00, fx_log3p[3:0]};
                    7'd44: charcode = 6'd19;
                    7'd45: charcode = {2'b00, fx_log3r[3:0]};
                    7'd46: charcode = 6'd19;
                    7'd47: charcode = {2'b00, fx_log3d[31:28]};
                    7'd48: charcode = {2'b00, fx_log3d[27:24]};
                    7'd49: charcode = {2'b00, fx_log3d[23:20]};
                    7'd50: charcode = {2'b00, fx_log3d[19:16]};
                    7'd51: charcode = {2'b00, fx_log3d[15:12]};
                    7'd52: charcode = {2'b00, fx_log3d[11:8]};
                    7'd53: charcode = {2'b00, fx_log3d[7:4]};
                    7'd54: charcode = {2'b00, fx_log3d[3:0]};
                    7'd56: charcode = {2'b00, fx_log4p[7:4]};
                    7'd57: charcode = {2'b00, fx_log4p[3:0]};
                    7'd58: charcode = 6'd19;
                    7'd59: charcode = {2'b00, fx_log4r[3:0]};
                    7'd60: charcode = 6'd19;
                    7'd61: charcode = {2'b00, fx_log4d[31:28]};
                    7'd62: charcode = {2'b00, fx_log4d[27:24]};
                    7'd63: charcode = {2'b00, fx_log4d[23:20]};
                    7'd64: charcode = {2'b00, fx_log4d[19:16]};
                    7'd65: charcode = {2'b00, fx_log4d[15:12]};
                    7'd66: charcode = {2'b00, fx_log4d[11:8]};
                    7'd67: charcode = {2'b00, fx_log4d[7:4]};
                    7'd68: charcode = {2'b00, fx_log4d[3:0]};
                    7'd70: charcode = {2'b00, fx_log5p[7:4]};
                    7'd71: charcode = {2'b00, fx_log5p[3:0]};
                    7'd72: charcode = 6'd19;
                    7'd73: charcode = {2'b00, fx_log5r[3:0]};
                    7'd74: charcode = 6'd19;
                    7'd75: charcode = {2'b00, fx_log5d[31:28]};
                    7'd76: charcode = {2'b00, fx_log5d[27:24]};
                    7'd77: charcode = {2'b00, fx_log5d[23:20]};
                    7'd78: charcode = {2'b00, fx_log5d[19:16]};
                    7'd79: charcode = {2'b00, fx_log5d[15:12]};
                    7'd80: charcode = {2'b00, fx_log5d[11:8]};
                    7'd81: charcode = {2'b00, fx_log5d[7:4]};
                    7'd82: charcode = {2'b00, fx_log5d[3:0]};
                    default: ;
                endcase
            end
            6'd39: begin
                case (tcol)
                    7'd0: charcode = {2'b00, fx_log6p[7:4]};
                    7'd1: charcode = {2'b00, fx_log6p[3:0]};
                    7'd2: charcode = 6'd19;
                    7'd3: charcode = {2'b00, fx_log6r[3:0]};
                    7'd4: charcode = 6'd19;
                    7'd5: charcode = {2'b00, fx_log6d[31:28]};
                    7'd6: charcode = {2'b00, fx_log6d[27:24]};
                    7'd7: charcode = {2'b00, fx_log6d[23:20]};
                    7'd8: charcode = {2'b00, fx_log6d[19:16]};
                    7'd9: charcode = {2'b00, fx_log6d[15:12]};
                    7'd10: charcode = {2'b00, fx_log6d[11:8]};
                    7'd11: charcode = {2'b00, fx_log6d[7:4]};
                    7'd12: charcode = {2'b00, fx_log6d[3:0]};
                    7'd14: charcode = {2'b00, fx_log7p[7:4]};
                    7'd15: charcode = {2'b00, fx_log7p[3:0]};
                    7'd16: charcode = 6'd19;
                    7'd17: charcode = {2'b00, fx_log7r[3:0]};
                    7'd18: charcode = 6'd19;
                    7'd19: charcode = {2'b00, fx_log7d[31:28]};
                    7'd20: charcode = {2'b00, fx_log7d[27:24]};
                    7'd21: charcode = {2'b00, fx_log7d[23:20]};
                    7'd22: charcode = {2'b00, fx_log7d[19:16]};
                    7'd23: charcode = {2'b00, fx_log7d[15:12]};
                    7'd24: charcode = {2'b00, fx_log7d[11:8]};
                    7'd25: charcode = {2'b00, fx_log7d[7:4]};
                    7'd26: charcode = {2'b00, fx_log7d[3:0]};
                    7'd28: charcode = {2'b00, fx_log8p[7:4]};
                    7'd29: charcode = {2'b00, fx_log8p[3:0]};
                    7'd30: charcode = 6'd19;
                    7'd31: charcode = {2'b00, fx_log8r[3:0]};
                    7'd32: charcode = 6'd19;
                    7'd33: charcode = {2'b00, fx_log8d[31:28]};
                    7'd34: charcode = {2'b00, fx_log8d[27:24]};
                    7'd35: charcode = {2'b00, fx_log8d[23:20]};
                    7'd36: charcode = {2'b00, fx_log8d[19:16]};
                    7'd37: charcode = {2'b00, fx_log8d[15:12]};
                    7'd38: charcode = {2'b00, fx_log8d[11:8]};
                    7'd39: charcode = {2'b00, fx_log8d[7:4]};
                    7'd40: charcode = {2'b00, fx_log8d[3:0]};
                    7'd42: charcode = {2'b00, fx_log9p[7:4]};
                    7'd43: charcode = {2'b00, fx_log9p[3:0]};
                    7'd44: charcode = 6'd19;
                    7'd45: charcode = {2'b00, fx_log9r[3:0]};
                    7'd46: charcode = 6'd19;
                    7'd47: charcode = {2'b00, fx_log9d[31:28]};
                    7'd48: charcode = {2'b00, fx_log9d[27:24]};
                    7'd49: charcode = {2'b00, fx_log9d[23:20]};
                    7'd50: charcode = {2'b00, fx_log9d[19:16]};
                    7'd51: charcode = {2'b00, fx_log9d[15:12]};
                    7'd52: charcode = {2'b00, fx_log9d[11:8]};
                    7'd53: charcode = {2'b00, fx_log9d[7:4]};
                    7'd54: charcode = {2'b00, fx_log9d[3:0]};
                    7'd56: charcode = {2'b00, fx_log10p[7:4]};
                    7'd57: charcode = {2'b00, fx_log10p[3:0]};
                    7'd58: charcode = 6'd19;
                    7'd59: charcode = {2'b00, fx_log10r[3:0]};
                    7'd60: charcode = 6'd19;
                    7'd61: charcode = {2'b00, fx_log10d[31:28]};
                    7'd62: charcode = {2'b00, fx_log10d[27:24]};
                    7'd63: charcode = {2'b00, fx_log10d[23:20]};
                    7'd64: charcode = {2'b00, fx_log10d[19:16]};
                    7'd65: charcode = {2'b00, fx_log10d[15:12]};
                    7'd66: charcode = {2'b00, fx_log10d[11:8]};
                    7'd67: charcode = {2'b00, fx_log10d[7:4]};
                    7'd68: charcode = {2'b00, fx_log10d[3:0]};
                    7'd70: charcode = {2'b00, fx_log11p[7:4]};
                    7'd71: charcode = {2'b00, fx_log11p[3:0]};
                    7'd72: charcode = 6'd19;
                    7'd73: charcode = {2'b00, fx_log11r[3:0]};
                    7'd74: charcode = 6'd19;
                    7'd75: charcode = {2'b00, fx_log11d[31:28]};
                    7'd76: charcode = {2'b00, fx_log11d[27:24]};
                    7'd77: charcode = {2'b00, fx_log11d[23:20]};
                    7'd78: charcode = {2'b00, fx_log11d[19:16]};
                    7'd79: charcode = {2'b00, fx_log11d[15:12]};
                    7'd80: charcode = {2'b00, fx_log11d[11:8]};
                    7'd81: charcode = {2'b00, fx_log11d[7:4]};
                    7'd82: charcode = {2'b00, fx_log11d[3:0]};
                    default: ;
                endcase
            end
            default: ;
        endcase
    end
end

// ---------------------------------------------------------------------------
// 3x5 font (generated).
// ---------------------------------------------------------------------------
function automatic [14:0] glyph(input [5:0] c);
    case (c)
        6'd0: glyph = 15'b111101101101111;
        6'd1: glyph = 15'b010110010010111;
        6'd2: glyph = 15'b111001111100111;
        6'd3: glyph = 15'b111001011001111;
        6'd4: glyph = 15'b101101111001001;
        6'd5: glyph = 15'b111100111001111;
        6'd6: glyph = 15'b111100111101111;
        6'd7: glyph = 15'b111001001010010;
        6'd8: glyph = 15'b111101111101111;
        6'd9: glyph = 15'b111101111001111;
        6'd10: glyph = 15'b010101111101101;
        6'd11: glyph = 15'b110101110101110;
        6'd12: glyph = 15'b111100100100111;
        6'd13: glyph = 15'b110101101101110;
        6'd14: glyph = 15'b111100111100111;
        6'd15: glyph = 15'b111100111100100;
        6'd16: glyph = 15'b000000000000000;
        6'd17: glyph = 15'b000111000111000;
        6'd18: glyph = 15'b001001010100100;
        6'd19: glyph = 15'b000010000010000;
        6'd20: glyph = 15'b100010001010100;
        6'd21: glyph = 15'b000000111000000;
        6'd22: glyph = 15'b000000000000010;
        6'd23: glyph = 15'b111100101101111;
        6'd24: glyph = 15'b101101111101101;
        6'd25: glyph = 15'b111010010010111;
        6'd26: glyph = 15'b101110100110101;
        6'd27: glyph = 15'b100100100100111;
        6'd28: glyph = 15'b101111111101101;
        6'd29: glyph = 15'b111101101101101;
        6'd30: glyph = 15'b111101111100100;
        6'd31: glyph = 15'b111101101111001;
        6'd32: glyph = 15'b111101110101101;
        6'd33: glyph = 15'b111100111001111;
        6'd34: glyph = 15'b111010010010010;
        6'd35: glyph = 15'b101101101101111;
        6'd36: glyph = 15'b101101101101010;
        6'd37: glyph = 15'b101101111111101;
        6'd38: glyph = 15'b101101010101101;
        6'd39: glyph = 15'b101101010010010;
        default: glyph = 15'd0;
    endcase
endfunction

wire [14:0] grow = glyph(charcode);
logic [2:0] gslice;
always_comb begin
    case (tline)
        3'd0: gslice = grow[14:12];
        3'd1: gslice = grow[11:9];
        3'd2: gslice = grow[8:6];
        3'd3: gslice = grow[5:3];
        3'd4: gslice = grow[2:0];
        default: gslice = 3'd0;
    endcase
end
wire pix = (gx != 2'd3) && gslice[2'd2 - gx];

wire in_active = (hcnt < active_width) && (vcnt < active_height);

logic [23:0] rgb_r;
always_ff @(posedge clk) begin
    if (ce_pixel)
        rgb_r <= (en && in_active && pix) ? 24'hffffff : 24'h000000;
end

assign rgb_out = en ? rgb_r : rgb_in;

endmodule
