-- SPDX-License-Identifier: GPL-3.0-or-later
--
-- Drive MAME with the *exact* input schedule of the RTL scenario
-- `coin_start_p1_long` (verif/scenarios/dynagear/coin_start_p1_long.json,
-- generated by apply_inputs() in verif/tb_ssv_frame_crc.sv) and dump PPM
-- screenshots at chosen post-video-enable frame indices.
--
-- Purpose: when the RTL shows something odd at post-VE frame N, this answers
-- "does MAME show the same thing?" without guessing.
--
-- Frame origin: armed on the write to $21000E with bit 7 set, matching the
-- RTL's video_enable, exactly as tools/mame-capture-ssv-frames.lua does.  Post-
-- VE frame numbering therefore lines up with the testbench's `post_ve_frames`.
--
-- Environment:
--   SSV_PPM_PREFIX  output stem (default sim_output/mame/long/mame_long)
--   SSV_PPM_FRAMES  comma-separated post-VE frames to capture
--   SSV_MAX_FRAMES  stop after this many post-VE frames
--
-- NOTE: MAME and the RTL are not guaranteed cycle-identical this far in, so a
-- mismatch at one frame is a lead to investigate, not by itself a defect.

local WIDTH, HEIGHT = 336, 240
local prefix    = os.getenv("SSV_PPM_PREFIX") or "sim_output/mame/long/mame_long"
local max_frames = tonumber(os.getenv("SSV_MAX_FRAMES")) or 1400

local want = {}
for v in string.gmatch(os.getenv("SSV_PPM_FRAMES") or "", "[^,]+") do
    want[tonumber(v)] = true
end

local screen  = assert(manager.machine.screens[":screen"])
local maincpu = assert(manager.machine.devices[":maincpu"])
local program = assert(maincpu.spaces["program"])

local P1     = manager.machine.ioport.ports[":P1"]
local SYSTEM = manager.machine.ioport.ports[":SYSTEM"]
local F = {
    up    = P1.fields["P1 Up"],    down  = P1.fields["P1 Down"],
    left  = P1.fields["P1 Left"],  right = P1.fields["P1 Right"],
    b1    = P1.fields["P1 Button 1"], b2 = P1.fields["P1 Button 2"],
    b3    = P1.fields["P1 Button 3"],
    start = P1.fields["1 Player Start"],
    coin  = SYSTEM.fields["Coin 1"],
}

local frame = 0
local armed = false

-- Must be a global: a collected passthrough handler is silently removed.
ssv_long_ve_tap = program:install_write_tap(0x21000e, 0x21000f,
    "ssv_long_video_enable_arm",
    function(offset, data, mask)
        if (data & 0x80) ~= 0 then armed = true end
        return data
    end)

-- Mirrors verif/tb_ssv_frame_crc.sv apply_inputs() for coin_start_p1_long.
local function apply_inputs(f)
    for _, fld in pairs(F) do fld:set_value(0) end

    if f >= 30 and f < 34 then F.coin:set_value(1) end
    if f >= 165 and f < 170 then F.start:set_value(1) end
    if f >= 250 and f < 255 then F.start:set_value(1) end
    if f >= 255 and f < 262 then F.b1:set_value(1) end
    if f >= 300 and f < 330 then F.right:set_value(1) end
    if f >= 330 and f < 360 then F.b1:set_value(1) end
    if f >= 360 and f < 390 then F.up:set_value(1) end
    if f >= 420 and f < 425 then F.b1:set_value(1) end
    if f >= 480 and f < 485 then F.start:set_value(1) end
    if f >= 540 and f < 545 then F.b1:set_value(1) end
    if f >= 820 and f < 870 then F.right:set_value(1) end
    if (f >= 840 and f < 848) or (f >= 875 and f < 883) then F.b1:set_value(1) end
    if f >= 890 and f < 920 then F.up:set_value(1) end

    if f >= 950 then
        local c = (f - 950) % 240
        if c < 140              then F.right:set_value(1) end
        if c >= 200 and c < 220 then F.left:set_value(1) end
        if c >= 150 and c < 170 then F.up:set_value(1) end
        if c >= 176 and c < 190 then F.down:set_value(1) end
        if (c % 12) < 6         then F.b1:set_value(1) end
        if (c >= 60 and c < 66) or (c >= 170 and c < 176) then F.b2:set_value(1) end
        if c >= 232 and c < 236 then F.b3:set_value(1) end
        if ((f - 950) % 1800) < 5 then F.start:set_value(1) end
        if ((f - 950) % 3600) < 4 then F.coin:set_value(1) end
    end
end

local function write_ppm(f)
    local path = string.format("%s_f%04d.ppm", prefix, f)
    local fh = assert(io.open(path, "wb"))
    fh:write(string.format("P6\n%d %d\n255\n", WIDTH, HEIGHT))
    for y = 0, HEIGHT - 1 do
        local row = {}
        for x = 0, WIDTH - 1 do
            local p = screen:pixel(x, y)
            row[#row + 1] = string.char((p >> 16) & 0xff, (p >> 8) & 0xff, p & 0xff)
        end
        fh:write(table.concat(row))
    end
    fh:close()
    print(string.format("SSV_LONG_PPM frame=%d path=%s", f, path))
end

emu.register_frame_done(function()
    if manager.machine.paused or not armed then return end
    if frame >= max_frames then
        print(string.format("SSV_LONG_DONE frames=%d", frame))
        manager.machine:exit()
        return
    end
    if want[frame] then write_ppm(frame) end
    apply_inputs(frame)
    frame = frame + 1
end)

apply_inputs(0)
print(string.format("SSV_LONG_READY prefix=%s max_frames=%d", prefix, max_frames))
